name: Deploy Streamlit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install streamlit pandas

      - name: Deploy to Streamlit
        env:
          STREAMLIT_API_TOKEN: ${{ secrets.STREAMLIT_API_TOKEN }}
        run: |
          streamlit run streamlit_app.py
